controller_list:
  - name: /rv7f/rv7f_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6